{
 "title": "Processes Dashboard",
 "tags": [ "processes" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(host)" }
  ]
 },
 "panels": [
  {
   "title": "Node Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",host=\"$host\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{host=\"$host\"}",
     "legendFormat": "{{groupname}},{{host}}"
    }
   ]
  },
  {
   "title": "Yes processes CPU rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "  rate(namedprocess_namegroup_cpu_seconds_total{host=\"$host\"}[1m])",
     "legendFormat": "{{groupname}}-{{mode}}"
    }
   ]
  },
  {
   "title": "sleep processes count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=\"sleep_process\",host=\"$host\"    }",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}